### ISSUE TITLE
Blender portable auto copy the presets pack

### ISSUE THREAD

**Issue by zuppasoupnikmat** [Trantor2098/hot_node#9]
i don't know if this is feature or bug

I tried download blender 4.2.4 portable and do "fresh install" by extract to different hard drive
and do "portable" install (like in Blender documentation) 
https://docs.blender.org/manual/en/latest/advanced/blender_directory_layout.html (by just adding new folder named 'portable' )
and fresh download the hot nodes from extension, but it seems auto copy the pack from other portable blender from different drive and version

*the reason i do fresh install too here , is because ever since the blender 4.2.4 update on steam, seems the hot node is dissapear, despite its enabled (which i need to try to uninstall and install later)

Edit : After i tried to reinstall the Hot node in steam version (which is located in C:\Users\[USERNAME]\AppData\Roaming\Blender Foundation\Blender\4.2\extensions\blender_org )
seems also auto copy the presets pack from the portable folder

**Comment by Trantor2098** [comment]
Hi zuppasoupnikmat

> it seems auto copy the pack from other portable blender from different drive and version

This is because the Hot Node's auto-recover feature. Hot Node stores your preset at the add-on directory, which means you can have independent preset warehouse for each blender, but it also have a global folder at C disk which can be accessed by all your installed Hot Node. This global folder stores autosave files and do backups when updating the addon.

Everytime you open/close&enable/disable blender&addon it records the preset packs in your current active blender, and when you install/update/reinstall the Hot Node on the other blender, it will find the last auto saved packs and recover it, that's why it seemed there happened a "copy".

Thank you for mentioning this, reminded me of the sync problem between different blender versions.
Now I'm planning to separate the updating-backup and the auto-save module to avoid "copy".

> *the reason i do fresh install too here , is because ever since the blender 4.2.4 update on steam, seems the hot node is dissapear, despite its enabled (which i need to try to uninstall and install later)

Btw, is this occasional or does this happen often? Can you show the cmd infos once this happen again?

**Comment by Trantor2098** [comment]
Solve copy issue may take a few months... Maybe you need to use the mechanism mentioned above to have a temp solution for now... And use `Export All` to backup your packs is always a good action.

**Comment by zuppasoupnikmat** [comment]
> And use Export All to backup your packs is always a good action
Yeah for now i just backup manually (since for example when i reinstall the hot node addon because hot node dont appear)

>Btw, is this occasional or does this happen often?
This is the first time i encounter it

> Solve copy issue may take a few months...
No worries, thank you very much for your support, just want to let you know about this

**Comment by Trantor2098** [comment]
OK, notes were taken. I will close this issue for now and you can reopen if need. : )
